<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Codebasics/blob/main/K_fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
from sklearn.datasets import load_digits

In [171]:
digits = load_digits()

In [172]:
from sklearn.model_selection import train_test_split

In [173]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [184]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target, test_size = 0.3)

In [175]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [176]:
reg = LogisticRegression()
reg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [177]:
reg.score(X_test,y_test)

0.9722222222222222

In [178]:
model = SVC()
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [179]:
model.score(X_test,y_test)

0.9888888888888889

In [180]:
en = RandomForestClassifier()
en.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [181]:
en.score(X_test,y_test)

0.9777777777777777

In [182]:
from sklearn.model_selection import KFold

In [183]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [188]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [189]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [190]:
from sklearn.model_selection import StratifiedKFold

In [191]:
folds = StratifiedKFold(n_splits=3)

In [193]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index,test_index in kf.split(digits.data):
  X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
  

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [194]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [195]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [196]:
scores_rf

[0.9465776293823038, 0.9549248747913188, 0.9348914858096828]

In [197]:
from sklearn.model_selection import cross_val_score

In [198]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [199]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [200]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.94166667, 0.89722222, 0.95543175, 0.9637883 , 0.91922006])

# **Homework**

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [5]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [7]:
X = iris.data
y = iris.target

In [10]:
import numpy as np

In [6]:
from sklearn.model_selection import cross_val_score

In [9]:
lr_score = cross_val_score(LogisticRegression(),X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [11]:
np.average(lr_score )

0.9733333333333334

In [15]:
svm_score = cross_val_score(SVC(),X,y)

In [16]:
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [17]:
np.average(svm_score)

0.9666666666666666

In [18]:
dtc_score = cross_val_score(DecisionTreeClassifier(),X,y)

In [19]:
dtc_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [20]:
np.average(dtc_score)

0.9666666666666668

In [21]:
rfc_score = cross_val_score(RandomForestClassifier(),X,y)
rfc_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [22]:
np.average(rfc_score)

0.9666666666666668