<a href="https://colab.research.google.com/github/MadhurimaPaul-87/Codebasics/blob/main/Naive_Bayes_Classifier_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_cat = LabelEncoder()

In [9]:
df['Category_n'] = le_cat.fit_transform(df['Category'])
df

Category                                            Message  Category_n
0         ham  Go until jurong point, crazy.. Available only ...           0
1         ham                      Ok lar... Joking wif u oni...           0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...           1
3         ham  U dun say so early hor... U c already then say...           0
4         ham  Nah I don't think he goes to usf, he lives aro...           0
...       ...                                                ...         ...
5567     spam  This is the 2nd time we have tried 2 contact u...           1
5568      ham               Will ü b going to esplanade fr home?           0
5569      ham  Pity, * was in mood for that. So...any other s...           0
5570      ham  The guy did some bitching but I acted like i'd...           0
5571      ham                         Rofl. Its true to its name           0

[5572 rows x 3 columns]

In [11]:
df = df.drop(['Category'],axis=1)
df.head()

Message  Category_n
0  Go until jurong point, crazy.. Available only ...           0
1                      Ok lar... Joking wif u oni...           0
2  Free entry in 2 a wkly comp to win FA Cup fina...           1
3  U dun say so early hor... U c already then say...           0
4  Nah I don't think he goes to usf, he lives aro...           0

In [12]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['Category_n'],test_size = 0.25)

# **1st Method**

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer() 
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [36]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9870782483847811

# **2nd method**

In [37]:
from sklearn.pipeline import Pipeline

In [38]:
clf = Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [39]:
clf.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [40]:
clf.score(X_test,y_test)

0.9870782483847811

In [42]:
clf.predict(emails)

array([0, 1])

# **Homework**

In [43]:
from sklearn.datasets import load_wine

In [44]:
wine = load_wine()

In [45]:
dir(wine)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [46]:
import pandas as pd

In [47]:
df = pd.DataFrame(wine.data,columns=wine.feature_names)

In [48]:
df

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [49]:
df['target']=wine.target
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [51]:
df['names']= df.target.apply(lambda x: wine.target_names[x])
df

alcohol  malic_acid   ash  ...  proline  target    names
0      14.23        1.71  2.43  ...   1065.0       0  class_0
1      13.20        1.78  2.14  ...   1050.0       0  class_0
2      13.16        2.36  2.67  ...   1185.0       0  class_0
3      14.37        1.95  2.50  ...   1480.0       0  class_0
4      13.24        2.59  2.87  ...    735.0       0  class_0
..       ...         ...   ...  ...      ...     ...      ...
173    13.71        5.65  2.45  ...    740.0       2  class_2
174    13.40        3.91  2.48  ...    750.0       2  class_2
175    13.27        4.28  2.26  ...    835.0       2  class_2
176    13.17        2.59  2.37  ...    840.0       2  class_2
177    14.13        4.10  2.74  ...    560.0       2  class_2

[178 rows x 15 columns]

In [53]:
df_in = df.drop(['target','names'],axis=1)
df_in

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [54]:
df_tar = df['target']
df_tar

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split

In [57]:
X_train,X_test,y_train,y_test = train_test_split(df_in,df_tar,test_size=0.2)

In [58]:
from sklearn.naive_bayes import GaussianNB

In [59]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [61]:
nb.score(X_test,y_test)

0.9444444444444444

In [62]:
nb.predict(X_test)

array([1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2])

In [64]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [65]:
model.score(X_train,y_train)

0.8450704225352113

In [67]:
model.predict(X_test)

array([1, 1, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 1,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2])